events {}

http {

  server {
    listen 80;

    location /api/users {
      proxy_pass http://users-service:5001;
    }

    location /api/products {
      proxy_pass http://products-service:5002;
    }

    location /api/orders {
      proxy_pass http://orders-service:5003;
    }

  }

}
