events {}

http {

  server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location = /api/users {
      proxy_pass http://users-service:5001/users;
    }

    location /api/users/ {
      proxy_pass http://users-service:5001/users/;
    }

    location = /api/products {
      proxy_pass http://products-service:5002/products;
    }

    location /api/products/ {
      proxy_pass http://products-service:5002/products/;
    }

    location = /api/orders {
      proxy_pass http://orders-service:5003/orders;
    }

    location /api/orders/ {
      proxy_pass http://orders-service:5003/orders/;
    }
  }

}
